<?php

/**
 * Created by PhpStorm.
 * User: fate
 * Date: 15/10/15
 * Time: 下午4:24
 */
class AuthorizationModel extends \Net\Restful\Server\Handle
{
	public function UPDATE ($_service, $_resource, $_parameters, $_properties, $_request_body)
	{
		parent::UPDATE($_service, $_resource, $_parameters, $_properties, $_request_body); // TODO: Change the autogenerated stub
	}
}